### ISSUE TITLE
sources for the libraries

### ISSUE THREAD

**Issue by AndreiD** [bosch-io/iot-things-examples#4]
Hi,

In your examples you have:
~~~~
final Thing updated = thing.setAclEntry(aclEntry);
~~~~

marked as deprecated. 

But when I click it to see what's the new way to do it, I cannot see the sources. It's stuck at searching and when I click download from maven it gives me 

~~~~
Sources for 'cr-model-5.0.0.jar' not found
~~~~

My environment...

IntelliJ IDEA 2016.3.2

**Comment by bkueb** [comment]
Hi,

setAclEntry is deprecated because we are currently extending the the ACL mechanism for Things to a fine-grained Policy concept that allows access control for every element of a Thing. The management of Policies is not yet implemented for the Things client.

We will push the sources with the next Things client release to the maven repo.

/Björn

**Comment by ghandim** [comment]
Hi,
we released the client 3.0.0.RC9 with attached sources. 
See https://maven.bosch-si.com/#nexus-search;gav~~things-client~3.0.0.RC9~~.
Best regards, Michael

**Comment by AndreiD** [comment]
great. super..fantastic
but with your regards can I have some suggestions for my project too (check my other issue) 💃

**Comment by AndreiD** [comment]
when you have time ...if you have. it's open source so...all involved are benevolent
