### ISSUE TITLE
x

### ISSUE THREAD

**Issue by AndreiD** [bosch-io/iot-things-examples#5]
x

**Comment by thjaeckle** [comment]
Hi Dan.
Sorry we did not come earlier for providing feedback.

I had a look at your project. Really cool to see our client used "in the wild" :+1: 
I'm not such Spring a expert, so I mostly just looked at the `ThermometerService` which uses our client.

Looks functioning the way it is, but I have some suggestions:
- in https://github.com/AndreiD/jarvis/blob/master/src/main/java/jarvis/service/ThermometerService.java#L42 you set a "unit_id" to the same value as the thingId - why that? seems redundant
- you're working a lot with `.get(timeout, TimeUnit.SECONDS)` when using the CompletableFutures of our API which works well for prototyping in order to quickly get something running
  - if you however some day need code which doesn't block the used thread all the time, we recommend embracing the `CompletionStages` (`CompletableFuture` is also a `CompletionStage`) more, e.g. by returning CompletionStages in the `ThermometerService` methods and plugging different CompletionStages together where the `ThermometerService` is used
  - an additional benefit would also be that you don't have to handle the `InterruptedException | ExecutionException | TimeoutException` so often

But to be honest, we also do not provide a good example of doing that - you have to know the API of CompletionStage quite well for that. Again: in order to quickly get a working example using `.get()` is totally fine. We'll add that to our TODOs: #7

Some follow up questions:
Is the `CCS811` part of your project related to sending the data to Bosch IoT Things? I didn't see that. Would be more interesting to get real data instead of only simulated :)

I didn't execute your project, but I guess startup times with first starting Spring with a webserver are quite high. Do you need a webserver later or why did you decide to use Spring?


All in all: Very cool that you put so much effort in your project and in trying out Bosch IoT Things. Do you have suggestions for improvement in the client or other feedback regarding Bosch IoT Things?

**Comment by AndreiD** [comment]
Thanks a lot for the feedback. didn't knew about Completion Stages but it seems they are the future. I'll look into them. 

Indeed, the startup times are ~35 seconds on a raspberry pi 3 (intel joule 💰 too much). They are on the limit of annoyance let's say. I was thinking how to improve them, a solution is to write a script that generate the jar file and uploads it to the board. then start the jar file. and I want to do it with 1 click.  
No, I don't need a server.

CCS811 is a new chip for air quality CO2 & toxic stuff... I converted the driver to java and I planned to format my hdd after, so I threw it in here. I should refactor when I have some time. 

Playing with Bosch IOT this last weeks, yes, from a simple developer point of view I have some suggestions. In fact I have them written on a piece of paper because I was preparing for an interview,  One of the "advantages" was to be familiar with Bosh IOT, so I got familiar.
Unfortunately I didn't heard back from the management here in Sofia (maybe help 😄). I wish I could move to Germany, but it's not possible :(

### Suggestions list
- Improve the documentation by looking at the competition (IBM Watson, Microsoft IOT). In the current state the documentation looks like it was written by just one person super-hero. 
- Buy a SSL certificate for the testing page or add the sub-domain for the demo
- Some people prefer Python. Add some integrations with other languages
- Make a classic registration/login. A dashboard where users can re-download their tokens
- You know about android things right ? I don't think I can use your library directly there. If android-things will be the next big thing, why not start supporting it from the beginning for the advantage of being the first.
- the example with track my phone is a little useless maybe ? almost all phones are android/ios, and you can write a native app that tracks them and access all other sensors/camera on them if needed. What's the VALUE that Bosch adds it ? I would like to see the classical "weather station" or some water plant/air ...quality analyzer project.
- organize some competitions (give me a sign 🥇) with cool project that uses our Api wins "something"... a job at Bosch :))  
- I wonder why Java was chosen as the main language, since C is still the king in embedded. To run it you need a board with support for it, while a uC with Bluetooth (even with WiFi) is very cheap and suitable for mass production.
